config:
  aws:region: us-east-1
  pulumi-shared-storage-tidb:cluster-autoscaler-ca-version: "v1.26.2"
  pulumi-shared-storage-tidb:cluster-autoscaler-down-threshold: "0.5"
  pulumi-shared-storage-tidb:cluster-availability-zones: "3"
  pulumi-shared-storage-tidb:cluster-cidr-block: 10.0.0.0/16
  pulumi-shared-storage-tidb:cluster-env: dev
  pulumi-shared-storage-tidb:cluster-k8s-version: "1.26"
  pulumi-shared-storage-tidb:cluster-region: us-east-1
  pulumi-shared-storage-tidb:cluster-suffix: f01
  pulumi-shared-storage-tidb:control-plane-enabled: "false"
  pulumi-shared-storage-tidb:nodegroups:
    - capacityType: "SPOT"
      category: "control-plane"
      component: "default"
      exclusive: false
      instanceTypes: ["t2.medium"]
      max: 10
      min: 2
      multipleASGs: false
      tier: "standard"
      version: 0
    - capacityType: "ON_DEMAND"
      category: "control-plane"
      component: "pd"
      instanceTypes: ["t2.medium"]
      max: 6
      min: 3
      multipleASGs: true
      tier: "standard"
      version: 0
    - capacityType: "ON_DEMAND"
      category: "storage"
      component: "tikv"
      instanceTypes: ["t2.medium"]
      max: 9
      min: 3
      multipleASGs: true
      tier: "standard"
      version: 0
    - capacityType: "SPOT"
      category: "compute"
      component: "tidb"
      instanceTypes: ["t2.medium"]
      max: 10
      min: 2
      multipleASGs: false
      tier: "standard"
      version: 0
  pulumi-shared-storage-tidb:serverless-enabled: "false"
  pulumi-shared-storage-tidb:serverless-keyspaces:
    - externalIP: false
      name: "tenant-1"
      rootPassword: ""
      tidbReplicas: 1
    - externalIP: false
      name: "tenant-2"
      rootPassword: ""
      tidbReplicas: 1
  pulumi-shared-storage-tidb:serverless-namespace: tidb-serverless
  pulumi-shared-storage-tidb:serverless-pd-replicas: "3"
  pulumi-shared-storage-tidb:serverless-pd-storage-size: "10Gi"
  pulumi-shared-storage-tidb:serverless-pd-version: v7.1.0
  pulumi-shared-storage-tidb:serverless-tidb-replicas: "1"
  pulumi-shared-storage-tidb:serverless-tidb-version: v7.1.0
  pulumi-shared-storage-tidb:serverless-tikv-replicas: "3"
  pulumi-shared-storage-tidb:serverless-tikv-storage-size: "10Gi"
  pulumi-shared-storage-tidb:serverless-tikv-version: v7.1.0
  pulumi-shared-storage-tidb:tidb-operator-tag: v1.4.4
