config:
  aws:region: ap-southeast-1
  pulumi-tidb-serverless:aws-ebs-csi-driver-version: "2.19.0"
  pulumi-tidb-serverless:aws-load-balancer-controller: "1.5.4"
  pulumi-tidb-serverless:bastion-ami-id: "ami-0bdd2fa5f37cf0248"
  pulumi-tidb-serverless:bastion-enabled: "false"
  pulumi-tidb-serverless:bastion-instance-type: "t2.medium"
  pulumi-tidb-serverless:cluster-autoscaler-ca-version: "v1.26.2"
  pulumi-tidb-serverless:cluster-autoscaler-down-threshold: "0.5"
  pulumi-tidb-serverless:cluster-availability-zones: "3"
  pulumi-tidb-serverless:cluster-cidr-block: 10.0.0.0/16
  pulumi-tidb-serverless:cluster-env: dev
  pulumi-tidb-serverless:cluster-k8s-version: "1.26"
  pulumi-tidb-serverless:cluster-region: ap-southeast-1
  pulumi-tidb-serverless:cluster-suffix: f01
  pulumi-tidb-serverless:control-plane-enabled: "false"
  pulumi-tidb-serverless:metrics-server-chart-version: "3.11.0"
  pulumi-tidb-serverless:nodegroups:
    - capacityType: "SPOT"
      category: "control-plane"
      component: "default"
      exclusive: false
      instanceTypes: ["t2.medium"]
      max: 10
      desired: 3
      min: 1
      tier: "standard"
      version: 0
    - capacityType: "ON_DEMAND"
      category: "control-plane"
      component: "pd"
      instanceTypes: ["t2.medium"]
      max: 6
      min: 3
      numberASGs: 3
      tier: "standard"
      version: 0
    - capacityType: "ON_DEMAND"
      category: "storage"
      component: "tikv"
      instanceTypes: ["t2.medium"]
      max: 9
      min: 3
      numberASGs: 3
      tier: "standard"
      version: 0
    - capacityType: "ON_DEMAND"
      category: "storage"
      component: "tikv"
      instanceTypes: ["t2.medium"]
      max: 1
      desired: 0
      min: 0
      numberASGs: 1
      startAZ: 0
      allowEmptyGroup: false
      tier: "hot"
      version: 0
    - capacityType: "SPOT"
      category: "compute"
      component: "tidb"
      instanceTypes: ["t2.medium"]
      max: 10
      min: 2
      tier: "standard"
      version: 0
  pulumi-tidb-serverless:serverless-enabled: "false"
  pulumi-tidb-serverless:serverless-keyspaces:
    - internet: false
      name: "tenant-1"
      rootPassword: ""
      tidbReplicas: 0
    - internet: false
      name: "tenant-2"
      rootPassword: ""
      tidbReplicas: 0
  pulumi-tidb-serverless:serverless-namespace: tidb-serverless
  pulumi-tidb-serverless:serverless-pd-replicas: "3"
  pulumi-tidb-serverless:serverless-pd-storage-size: "10Gi"
  pulumi-tidb-serverless:serverless-pd-version: v7.1.0
  pulumi-tidb-serverless:serverless-suspend: "false"
  pulumi-tidb-serverless:serverless-tidb-replicas: "1"
  pulumi-tidb-serverless:serverless-tidb-version: v7.1.0
  pulumi-tidb-serverless:serverless-tikv-hot-replicas: "0"
  pulumi-tidb-serverless:serverless-tikv-replicas: "3"
  pulumi-tidb-serverless:serverless-tikv-storage-size: "10Gi"
  pulumi-tidb-serverless:serverless-tikv-version: v7.1.0
  pulumi-tidb-serverless:tidb-operator-tag: v1.4.4
